source 'https://rubygems.org'

ruby '~> 3.4.0'

# Use the local engine gem
gem 'rails_mcp_engine', path: '..'

gem 'rails', '~> 8.0'

group :development, :test do
  gem 'capybara'
  gem 'puma', '~> 6.4'
  gem 'selenium-webdriver'
end
