require 'fast_mcp'

FastMcp.mount_in_rails(
  Rails.application,
  name: 'manual-app-mcp-server',
  version: '1.0.0',
  path_prefix: '/mcp',
  localhost_only: false # Allow remote connections
) do |server|
  Rails.application.config.after_initialize do
    # Manually trigger tool generation since to_prepare might run too late
    RailsMcpEngine::Engine.build_tools!

    # Register all tools generated by the engine
    # The engine generates tools inheriting from ApplicationTool (which inherits from FastMcp::Tool)
    server.register_tools(*ApplicationTool.descendants)
  end
end
